### ISSUE TITLE
보충

### ISSUE THREAD

**Issue by Dongyeongkim** [suhdonghwi/qubit#1]
보면서 상당히 이쁜 느낌이 드는 교육자료로 활용하기 좋겠다라는 생각이 들었어요.

보면서 3가지 정도 더 다루어줬으면 하는 게 있습니다.

슈미츠 분해, 양자상태/에러에 대한 구별법으로 폰노이만 방법/ POVM 방법, 결잃음이라고 하는 부분에 대해서 다뤄주시면 감사할 것 같아요!

**Comment by suhdonghwi** [comment]
감사합니다! 이후에 언급해주신 개념에 대해 더 학습하고 추가하도록 하겠습니다 👍
